language: objective-c

osx_image: xcode61

before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
  - sudo easy_install cpp-coveralls

script:
  - xctool clean build -project AutoLayout.xcodeproj -scheme AutoLayout
  - xctool test -project AutoLayout.xcodeproj -scheme AutoLayout

after_success:
  - ./script/coveralls.sh
